create table llx_digirisk_legaldisplay
(
  rowid                       integer AUTO_INCREMENT PRIMARY KEY,
  ref                         varchar(128) NOT NULL,
  ref_ext                     varchar(255) default NULL,
  entity                      integer default 1,
  date_creation               datetime default NULL,
  tms                         timestamp,
  description                 text,
  fk_socpeople_labour_doctor        integer default NULL,
  fk_socpeople_labour_inspector     integer default NULL,
  fk_soc_samu                 integer default NULL,
  fk_soc_pompiers             integer default NULL,
  fk_soc_police               integer default NULL,
  fk_soc_urgency              integer default NULL,
  fk_soc_rights_defender      integer default NULL,
  fk_soc_antipoison           integer default NULL,
  fk_soc_responsible_prevent  integer default NULL,
  note_consigne_detaillee     varchar(255),
  note_derogation_permanente  varchar(255),
  note_derogation_occas       varchar(255),
  note_convention_collective  varchar(255),
  note_lieu_cc                varchar(255),
  note_accord_participation   varchar(255),
  note_lieu_du                varchar(255),
  import_key                  integer default NULL,
  status                      smallint,
  fk_user_creat               integer default NULL,
  fk_user_modif               integer default NULL,
  last_main_doc               varchar(255),
  model_pdf                   varchar(255),
  model_odt                   varchar(255),
  note_affich                 varchar(255)

)ENGINE=innodb;
